### DISCUSSION TITLE
Wrong documentation about DB auth?

### DISCUSSION THREAD

**Discussion by DenisBY** [keephq/keep#3071] [General]
I tried to follow documentation about auth and tried to set according https://docs.keephq.dev/deployment/authentication/db-auth 
```
  keep-backend:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-api
    environment:
      - PORT=8080
      - AUTH_TYPE="DB"
...
```

but getting error:
```
keep-backend-1           | NotImplementedError: authverifier for "db" not implemented
```
What I'm doing wrong?

I found `docker-compose-with-auth.yml` which has `AUTH_TYPE=SINGLE_TENANT` but it's not mentioned anywhere in the docs. Or I'm looking at the wrong place?
