### DISCUSSION TITLE
How to ensure that an unsuccessful HTTP request does not lead to a workflow error?

### DISCUSSION THREAD

**Discussion by roma55443** [keephq/keep#4507] [Q&A] [answered]
Task:
I need to check if a channel already exists in the messenger before creating a new channel.

Problem:
When I send a request to check if the channel exists (using the HTTP Step), and the channel is not found, the messenger returns an error with code 400. As a result, this error breaks the entire workflow since status 400 is treated as a failure.

Goal:
I need to configure the HTTP request handling so that when the channel doesn’t exist (and a 400 status code is returned), it does not cause an error and does not interrupt the workflow. Instead, the result of this step should be used as a condition for creating a new channel.

**Comment by dosubot** [comment]
To handle the HTTP 400 status code without causing a workflow error, you can use conditional logic to interpret the response and decide the next action. While I couldn't find a specific way to configure the HTTP Step to ignore error codes like 400, you can use the response in a conditional step to decide whether to proceed with creating a new channel.

Here's an example of how you might structure your workflow:

```yaml
steps:
  - name: check-channel
    provider:
      type: http
      with:
        url: "https://api.messenger.com/check-channel"
    on-failure:
      retry:
        count: 0  # No retries, handle the error in the next step

actions:
  - name: create-channel
    if: "{{ steps.check-channel.results.status_code == 400 }}"
    provider:
      type: http
      with:
        url: "https://api.messenger.com/create-channel"
        method: POST
        body:
          name: "new-channel"
```

In this setup, the `create-channel` action is only triggered if the `check-channel` step returns a 400 status code, indicating that the channel does not exist. This way, the workflow continues without treating the 400 status code as a failure.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/409207f6-1301-4873-aaab-9b8df9d022e0?feedback_type=other)</sup>
