### DISCUSSION TITLE
I want to integrate a LiteLLM into Keep and access the latter by Istio VirtualService

### DISCUSSION THREAD

**Discussion by Cyberphysics** [keephq/keep#4616] [Ideas]
I want to install Keep  keep-0.1.83 by helm chart in local k8s cluster.

```
#Add the Helm repository
helm repo add keephq https://keephq.github.io/helm-charts
#Install Keep with ingress enabled
helm install keep keephq/keep  -n keep --create-namespace
```

And there are not nginx ingress but a istio ingress in the cluster, so I create a virtualservice of istio in namespace keep which only match / and destination is keep-frontend 3000 port, I access 'keep.example.work' and click main entries list, that's ok, and then I add one Prometheus instance in data source page and saved, one night passed, I access Keep page and found no alerts, it may be normal.

Then I want to integrate a LiteLLM into Keep.

```
# And I remember it's ok before Keep integrate LiteLLM pod which proxy a ollama service.
# And I execute commands like:
`helm pull oci://ghcr.io/berriai/litellm-helm --version 0.1.658
tar -zxvf litellm-helm-0.1.658.tgz
helm install lite-helm ./litellm-helm \
  --namespace keep --create-namespace
```

I have access LiteLLM by port-forward the svc and see the Ollama LLM deepseek/deepseek-r1:70b is online.
Then I view the http://keep.example.work/ and found it wrong after some seconds and raise error like:
```
91183-b30f96707b76b673.js:1 WebSocket connection to 'wss://keep.example.work/websocket/app/keepappkey?protocol=7&client=js&version=8.4.0&flash=false' failed:
......
```

It looks like websocket svc has been routed bad, so I applyed istio virtualservice yaml file  below for routing different types of requests separately; I try modify some rewrite configuration in Istio VirtualService, remove the prefix which include / in tail, it works! 

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keep-virtualservice
  namespace: keep
spec:
  hosts:
  - keep.example.work
  gateways:
  - all-example-work-gw
  http:
  - name: api-route
    match:
    - uri:
        prefix: /v2/
    rewrite:
      uri: /         # delete /v2
    route:
    - destination:
        host: keep-backend
        port:
          number: 8080

  - name: ws-route
    match:
    - uri:
        prefix: /websocket/
    rewrite:
      uri: /              # delete /websocket
    route:
    - destination:
        host: keep-websocket
        port:
          number: 6001


  - name: frontend-route
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keep-frontend
        port:
          number: 3000
```
So I maybe contribute my way of making it work!
