### ISSUE TITLE
Keep provider should allow getting last workflow execution result

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1028]
So we can make the github-stars example work again (after removing the old state mechanism https://github.com/keephq/keep/pull/1007).
Workflow should be able to get X last workflow executions and their results.

**Comment by talboren** [comment]
In #1029 I suggest a different approach where we add the last workflow execution to the context manager.
It might create "race" conditions if workflow interval is too often but I think it's good enough for now.

Workflow example:
```yaml
id: new-github-stars
description: Notify Slack about new GitHub star for keephq/keep
triggers:
  - type: manual
  - type: interval
    value: 300
owners: []
services: []
steps:
  - name: get-github-stars
    provider:
      config: "{{ providers.github }}"
      type: github.stars
      with:
        previous_stars_count:
          default: 0
          key: "{{ last_workflow_results.get-github-stars.0.stars }}"
        repository: keephq/keep
```

Main difference is: **`key: "{{ last_workflow_results.get-github-stars.0.stars }}"`**

@shahargl lmk wdyt
