### ISSUE TITLE
Improve the "foreach" mechanism to be more solid

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#104]
# Current state
When running alert in "foreach" mode, the foreach context can be accessed via {{ foreach.value }}

For example, let's consider the next step:
```
    - name: check-disk-defects
      provider:
        type: postgres
        config: "{{ providers.postgres-server }}"
        with:
          query: "select * from disk"
      foreach: "{{ steps.this.results }}"
      condition:
        - name: threshold-condition
          type: threshold
          value:  " {{ foreach.value[13] }} " # disk defect is the 13th column
          compare_to: 50, 40, 30
          level: major, medium, minor
```
We can see that when we use ` foreach: "{{ steps.this.results }}"` every column can be accessed via " {{ foreach.value[i] }} "

But now we have a problem - the condition applies a level to each foreach - `level: major, medium, minor`, how can we store it as context so it'll be accessible via ` {{ foreach.level }}`?

So the current workaround for that is to add **kwargs to `set_condition_results` so every other context (e.g. `level`) will be stored in the additional context.

# What needs to be done
We need to design a better way for the `foreach` mechanism. I thought maybe using some contextmanager (e.g. __enter__ and __exit__ every time you are in foreach mode) or even treating the foreach context as a dataclass or something
