### ISSUE TITLE
Private presets are being pushed as part of `async-presets` message

### ISSUE THREAD

**Issue by talboren** [keephq/keep#1163]
Even if the preset is private, it's still being added to users who doesn't own the preset

**Comment by Savokr** [comment]
Hey @talboren, I am trying to properly reproduce the bug but creating new users from the UI is failing, saying that "password is required". Is there a simple way how I can test private presets, possibly via an API or otherwise, how can I fix the password problem during user creation. Here is the screenshot for when I am trying to add new users:

<img width="1726" alt="image" src="https://github.com/user-attachments/assets/7b9cb014-64a8-4485-9ae3-42c462adb322">

**Comment by soylent-grin** [comment]
@Savokr you need to run in `SINGLE_TENANT` mode (default is `NO_AUTH`). For example, add this in `docker-compose.dev.yml`
```
  keep-frontend-dev:
    environment:
      - AUTH_TYPE=SINGLE_TENANT
  ...
  keep-backend-dev:
    environment:
      - AUTH_TYPE=SINGLE_TENANT
      - KEEP_JWT_SECRET=verysecretkey
      - KEEP_DEFAULT_USERNAME=keep
      - KEEP_DEFAULT_PASSWORD=keep
```
