### ISSUE TITLE
How to connect prometheus (Alert manager ) with keep

### ISSUE THREAD

**Issue by chungngocnguyen** [keephq/keep#1237]
I used Alert manager with the following configuration:
```
routes:
 receiver: "keep"
 group_by: ['alertname']
 group_wait: 15s
 group_interval: 15s
 repeat_interval: 1m
 continue: true

receivers:
- name: "keep"
 webhook_configs:
 - url: 'http://0.0.0.0:8080/alerts/event/prometheus'
 send_resolved: true
 http_config:
 basic_auth:
 username: api_key
 password: 6a1ab117-dadb-44bb-b434-449b8a527f8a
```
I use no_auth mode in KEEP.
Alert manager reports error "cannot have continue in root route". I have read KEEP's Doc but there is no Doc for prometheus provider. Please help me review. Thank you.

**Comment by 35C4n0r** [comment]
@chungngocnguyen can you try removing `continue: true` from the routes

```
route:
  receiver: "keep"
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

receivers:
  - name: "keep"
    webhook_configs:
      - url: 'http://0.0.0.0:8080/alerts/event/prometheus'
        send_resolved: true
        http_config:
          basic_auth:
            username: api_key
            password: 6a1ab117-dadb-44bb-b434-449b8a527f8a
```

https://prometheus.io/docs/alerting/latest/configuration/#route
