### ISSUE TITLE
[🔌 Provider]: Webhook Provider

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#1685]
Add a webhook provider that will let you:
1. configure URL, headers and authentication
2. when used (`_notify`) will use the body and method (could be `POST` by default) from the `_notify` parameters
3. add workflow example for usage

should be something like
```
workflow:
  id: trigger-webhook-workflow
  triggers:
  - type: manual
  actions:
    - name: trigger-webhook
      provider:
        type: webhook
        config: '{{ providers.webhook }}'
        with:
          method: POST
          body:
            alert: {{ alert }}

```
