### ISSUE TITLE
Getting an error while trying to Create User

### ISSUE THREAD

**Issue by gjolps** [keephq/keep#2008]
**Describe the bug**
I'm trying to add authentication to keep and when I'm trying to create user from the Keep UI, I get an internal server error. 
I've installed keep using helm and running the latest version.
Below are the logs from keep-backend : 
```
  File "/venv/lib/python3.11/site-packages/keep/api/routes/auth/users.py", line 88, in create_user
    return identity_manager.create_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NoAuthIdentityManager.create_user() got an unexpected keyword argument 'user_email'
```
I also tried to enable database auth by adding ENV vars in values.yml but that did enable authentication. Below are the changes made to the values.yml.
```
backend:
  enabled: true
  env:
    - name: AUTH_TYPE
      value: DB
    - name: KEEP_JWT_SECRET
      value: verysecretkey
    - name: KEEP_DEFAULT_USERNAME
      value: keep
    - name: KEEP_DEFAULT_PASSWORD
      value: keep
frontend:
  enabled: true
  env:
    - name: AUTH_TYPE
      value: DB
```

**To Reproduce**
1. Go to Keep -> Settings -> Users and Access -> Users
2. Click on Add User
3. Enter Email, Name and select Role
4. See error "Error while saving user . An internal server error occurred." 

**Expected behavior**
User needs to be listed under the Users tab.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [130.0.1 (64-bit)]
