### ISSUE TITLE
Step retry mechanism

### ISSUE THREAD

**Issue by talboren** [keephq/keep#239]
**Is your feature request related to a problem? Please describe.**
Sometimes when a step fails to run (e.g. a simple HTTP request), I'd like to be able to have a retry mechanism before failing the step.

**Describe the solution you'd like**
An optional retry mechanism for steps to define what to do when a step fails.

**Describe alternatives you've considered**
-

**Additional context**
Requested by @configurator

**Comment by Abhishek-90** [comment]
@talboren correct if I misunderstoof your concern, basically you want an option like a `Retry button` so that you can restart the failed step correct? 

can you provide a screenshot or design?

**Comment by talboren** [comment]
@Abhishek-90 actually I meant the YAML spec.

This is something I've imagined that could potentially work:
```yaml
# Alert if a result queried from the DB is above a certain thershold.
alert:
  id: raw-sql-query
  description: Monitor that time difference is no more than 1 hour
  steps:
    - name: get-max-datetime
      provider:
        type: mysql
        config: "{{ providers.mysql-prod }}"
        with:
          # Get max(datetime) from the random table
          query: "SELECT MAX(datetime) FROM demo_table LIMIT 1"
        on-failure:
            retry: 3
  actions:
    - name: trigger-ntfy
      condition:
      - name: threshold-condition
        type: threshold
...
```

If step `get-max-datetime` fails, it'll retry the step 3 times before failing the workflow.
