### ISSUE TITLE
[🐛 Bug]: Adding multiple actions in a condition won't save both actions

### ISSUE THREAD

**Issue by maxlevinps** [keephq/keep#2911]
**Describe the bug**
As a user I want to define a workflow with a condition based on alert label match so I can have two different flows based on it.

**To Reproduce**
Build a workflow like the one in this image:
![image](https://github.com/user-attachments/assets/45bc1bb3-dc15-4058-87ae-45309a4b8520)

Hitting "Get YAML" returns the following YAML:
```
id: 8a72b5b0-20e7-4ad6-90f1-1e1686366b42
name: conditionsssssss
triggers:
  - type: manual
description: test
disabled: false
owners: []
services: []
consts: {}
steps: []
actions:
  - name: slack-action
    provider:
      type: slack
      config: "{{ providers.test }}"
      with:
        message: message
        channel: keep-groundcover
    condition:
      - name: Assert
        type: assert
        value: ""
        compare_to: ""
```

**Expected behavior**
Expected to see multiple actions in the actions section.
