### ISSUE TITLE
[📃 Docs]: disposable and enrich alert in trigger interval or manual (from workflow page) or incident

### ISSUE THREAD

**Issue by 00041275** [keephq/keep#2995]
My question is in the context of enrichment in the resolve_old_alert case
1) what does disposable true do?
2) how does the enrichment rule work if you don't have an alert in the trigger?
3) can I call subprocess in trigger interval or other with sending variables (for queried alerts in keep) ?? 

I currently have a case with zabbix, when I get data from it, but I don't know about resolving data. In an attempt to poll it again, I want to write updated data to alert for scope in trigger interval or manual (from workflow page) or incident. How I can poll and enrich using a trigger?

```
id: resolve-old-alerts
description: '-'
disabled: true
triggers:
- type: manual
- type: interval
  value: 60
consts: {}
name: resolve-old-alerts
owners: []
services: []
steps:
- name: get-alerts
  provider:
    config: '{{ providers.default-keep }}'
    type: keep
    with:
      filter: status == 'firing'
      version: 2
actions:
- foreach: ' {{ steps.get-alerts.results }} '
  if: keep.to_timestamp('{{ foreach.value.lastReceived }}') < keep.utcnowtimestamp() - 3600
  name: resolve-alerts
  provider:
    config: '{{ providers.default-mock }}'
    type: mock
    with:
      enrich_alert:
      - disposable: true
        key: status
        value: resolved
```

**Comment by 00041275** [comment]
@shahargl can you answer for question
In case for interval, enrichment work if object have variable "fingerprint". So if I want enrich alert with provider data I need get data from keep alerts, then get data from some provider, then create list[dict] may be in python provider where I merge alert data and provider data (and variable "fingerprint" is requirement for 1st lvl). Is it right? 

for example

steps:
  - get-alerts-from-keep
  - get-external-data-from-some-provider
  - transform_data_in_provider
[
{
"alert": {keep alert info},
"fingerprint": "asdsdfrege4324t3",
"external_data": {data from provider}
}
]

```
actions:
- foreach: ' {{ steps.transform_data_in_provider.results }} '
  if: {{ foreach.value.external_data.good }} == true
  name: resolve-alerts
  provider:
    config: '{{ providers.default-mock }}'
    type: mock
    with:
      enrich_alert:
      - disposable: true
        key: status
        value: resolved
      - key: external_data
        value: some_enrichment
```
