### ISSUE TITLE
[🐛 Bug]: workflow trigger interval work just with int

### ISSUE THREAD

**Issue by 00041275** [keephq/keep#3003]
syntax trigger for interval must be in 5m or cron, but we just can set int value.

### Interval Trigger

Runs workflows at a regular time interval or using a CRON expression.

```yaml
triggers:
  - type: interval
    # Run every 5 minutes
    value: 5m
```

```yaml
triggers:
  - type: interval
    # Run daily at 11:00 AM and 2:00 PM
    cron: "0 11,14 * * *"
```

## keep/parser/parser.py
```
    def parse_interval(self, workflow) -> int:
        # backward compatibility
        workflow_interval = workflow.get("interval", 0)
        triggers = workflow.get("triggers", [])
        for trigger in triggers:
            if trigger.get("type") == "interval":
                workflow_interval = trigger.get("value", 0)
        return workflow_interval
```
