### ISSUE TITLE
[➕ Feature]: PagerDuty Provider Allow passing any custom details on API call

### ISSUE THREAD

**Issue by maxlevinps** [keephq/keep#3189]
**Is your feature request related to a problem? Please describe.**
Currently keep PagerDuty provider lets me as a user send in the `custom_details` only a specific field named: `alert_body`. 
Keep should let me use any `key:value` pairs when sending alerts to PagerDuty as this is an object field in the docs.
The `alert_body` should not be required as well, as it's not a must in the API.
There are some other optional parameters in payload that we can pass other then `custom_details` see attached docs, for example: component, group, etc.
 
I've seen that grafana for example, send also `details` under `payload` field, this is undocumented, but maybe you should allow it as well. 

**Describe the solution you'd like**
Sample workflow which I expect to work after adding this feature:
```yaml
workflow:
  id: pagerduty_workflow
  description: Workflow for sending alerts to PagerDuty
  triggers:
  - type: alert
  name: pagerduty_workflow
  actions:
  - name: pagerduty-alert
    provider:
      config: '{{ providers.pager }}'
      type: pagerduty
      with:
        environment: prod
        service_name: app
        title: alert title
```

**Additional context**
Docs of PagerDuty API: https://developer.pagerduty.com/docs/send-alert-event
