### ISSUE TITLE
[➕ Feature]: Workflows Should Support Exclusion Filters for Events

### ISSUE THREAD

**Issue by maxlevinps** [keephq/keep#3223]
## Is your feature request related to a problem? Please describe.
Currently, `workflow.trigger.filters` only allow **inclusion-based filtering**, meaning users can specify which events should be processed. However, there is no built-in way to **explicitly exclude certain events**, which can lead to extra overhead when managing unwanted alerts.

For example, I want to **process only certain environments (`env: prod`)** but also **ensure that events from specific apps (`app: clickhouse.*`) are ignored**.

## Describe the solution you'd like
I propose extending the `filters` logic to include a simple boolean flag, `exclude: true`, for explicit exclusions. By default, filters remain **inclusion-based** unless `exclude` is set.

### Example YAML Workflow Configuration
This example defines a workflow where:
- Only events with `env: prod` are processed by default.
- Events where `app` matches `clickhouse.*` are **excluded** using `exclude: true`.

```yaml
workflow:
  id: workflow_with_filters
  description: Send a Slack message on alerts
  triggers:
    - type: alert
      filters:
        - key: env
          value: prod
        - key: app
          value: r"clickhouse.*"
          exclude: true
  actions:
    - name: trigger-slack-alert
      provider:
        type: slack
        config: '{{ providers.slack }}'
        with:
          message: '{{ alert }}'
```

## Describe alternatives you've considered
One alternative is crafting complex regex patterns to implicitly exclude events, but this approach:

- Is less readable and harder to maintain.
- Requires deeper regex knowledge.
- Doesn’t easily scale for multiple exclusions.

By using `exclude: true`, we keep the configuration simple, readable, and maintainable.
