### ISSUE TITLE
[🐛 Bug]: uploading YAML with the same id as existed workflow, overriding it not creating new

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#3324]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Matvey-Kuk** [comment]
I think that's an expected behaviour. That's why we need an ID :)

**Comment by Kiryous** [comment]
@Matvey-Kuk actually, comparison is done not by id but by name.

e.g. uploading two these workflows result in one workflow being overriden.

```yaml
workflow:
  id: test_id_2
  name: test_name_1
  actions:
    - name: echo
      provider:
        config: "{{ providers.default-console }}"
        type: console
        with:
          message: "{{alert.payload.summary}}"
  consts: {}
  description: playwright_test_add_upload_workflow_with_alert_trigger
  disabled: false
  owners: []
  services: []
  steps: []
  triggers:
    - filters:
        - key: source
          value: prometheus
      type: alert
```

```yaml
workflow:
  id: test_id_2
  name: test_name_1
  actions:
    - name: echo
      provider:
        config: "{{ providers.default-console }}"
        type: console
        with:
          message: "{{alert.payload.summary}}"
  consts: {}
  description: playwright_test_add_upload_workflow_with_alert_trigger
  disabled: false
  owners: []
  services: []
  steps: []
  triggers:
    - filters:
        - key: source
          value: prometheus
      type: alert
```
