### ISSUE TITLE
[🐛 Bug]: Test Run of a new workflow

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#3679]
1. I create a new workflow
2. I don't save it explicitly
3. I do test-run
4. It stuck in this screen:

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/e2952363-4289-43bb-bd84-22bbb45297b4" />

If I save it and run, I get a pretty confusing execution screen without logs.

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/8ebe2d86-2755-4c71-9983-e6d8aed5ea9f" />

Workflow YAML:

```
workflow:
  id: 95084d48-f72e-431c-a689-26f5fde421e9
  name: Dummy Workflow
  description: A sample workflow for demonstration purposes.
  disabled: false
  triggers:
    - type: manual
  consts: {}
  owners: []
  services: []
  steps: []
  actions:
    - name: console
      provider:
        config: "{{ providers.default-console }}"
        type: console
        with:
          message: Hello, this is a dummy workflow execution.
```
