### ISSUE TITLE
[🐛 Bug]: Sometimes I can run workflows, sometimes I can't

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#3680]
Such a workflow:

<img width="550" alt="Image" src="https://github.com/user-attachments/assets/64c05853-75ab-4290-b631-7cf8e1682e8b" />

```
workflow:
  id: 236fe306-560b-4453-a1bf-c3ec160dfab5
  name: incident-update-to-slack
  description: Share Incident Updates to Slack
  disabled: false
  triggers:
    - events:
        - created
      type: incident
  consts: {}
  owners: []
  services: []
  steps: []
  actions:
    - name: slack-action
      provider:
        config: "{{ providers.keephq }}"
        type: slack
        with:
          channel: C06PF9TCWUF
          message: "New incident: {{ incident.user_generated_name }} https://platform.keephq.dev/incidents/{{incident.id}}"
```

I can click "Test run" but not "Run" from the editor. I also can't run it from the list:

<img width="415" alt="Image" src="https://github.com/user-attachments/assets/b8caed35-4713-4e5c-ad30-375b033cae98" />

But If I test-run it from the editor, I get an exception:

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/40c7d235-6cb7-40e8-87c4-6e96d0a61a75" />
