### ISSUE TITLE
[🐛 Bug]: adding `enrich_alert` at the step level do not raise error

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#3825]
**Describe the bug**
if the `enrich_alert` or any other key is misplaced it should not just disappear, the specific error should be thrown and frontend should highlight the line it happen.

example of workflow where enrich_alert will disappear:
```
workflow:
  id: 877ad326-16f5-4e68-87a0-de16b4eae105
  name: alerts_enrich  
  description: alerts_enrich
  disabled: false
  triggers:
    - type: alert
      filters:
        - source: gcpmonitoring
  consts: {}
  owners: []
  services: []
  steps:
    - name: console-step
      provider:
        type: console
        config: "{{ providers.default-console }}"
        enrich_alert:
          - key: "hellew"
          - value: "hellew"
        with:
          message: alert should be enriched with hellew="hellew"
  actions: []
```
