### ISSUE TITLE
[🐛 Bug]: Faulty action breaks triggers in workflows

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#3832]
Trying such a workflow, I could run it:
```
id: retrieve-cloudwatch-logs
name: Retrieve CloudWatch Logs
description: Retrieve CloudWatch Logs
triggers:
  - type: manual

steps:
  - name: cw-logs
    provider:
      config: "{{ providers.cloudwatch }}"
      type: cloudwatch
      with:
        log_groups: 
         - "meow_logs"
        query: "fields @message | sort @timestamp desc | limit 20"
        hours: 4000
        remove_ptr_from_results: true
  ```

<img width="625" alt="Image" src="https://github.com/user-attachments/assets/ad886407-abd0-4e84-af99-1a148d0823a3" />

Trying to add faulty action:
```
id: retrieve-cloudwatch-logs
name: Retrieve CloudWatch Logs
description: Retrieve CloudWatch Logs
triggers:
  - type: manual

steps:
  - name: cw-logs
    provider:
      config: "{{ providers.cloudwatch }}"
      type: cloudwatch
      with:
        log_groups: 
         - "meow_logs"
        query: "fields @message | sort @timestamp desc | limit 20"
        hours: 4000
        remove_ptr_from_results: true
  

actions:
  - name: print-logs
    if: keep.len({{ steps.cw-logs.results }}) > 0
    type: print
    with:
      message: "{{ steps.cw-logs.results }}"
```
And UI says there is no manual trigger:

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/cfe0862d-07a2-44f3-89ed-6f27741dc41c" />
