### ISSUE TITLE
[🐛 Bug]: Workflow builder complains on a workflow which works fine

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#3872]
Workflow has:
- No descritpion
- "Mock" provider used as a base for enrichments
- Trigger

When I switch to the Builder, it's complaining about all 3 issues while workflow works fine with them. Should it complain?

```
workflow:
  id: enriching
  name: Enrich
  triggers:
    - type: alerts
      filters:
        - key: source
          value: prometheus
  actions:
    - name: enrich-alert
      provider:
        type: mock
        with:
          enrich_alert:
            - key: enriched_field_name
              value: "{{ alert.labels.pod }}"
```

Builder doesn't feel well:

<img width="1582" alt="Image" src="https://github.com/user-attachments/assets/14854c64-ab67-4403-920c-0c4ac9e63b3e" />
