### ISSUE TITLE
[🐛 Bug]: Argocd provider fails on multi-source apps

### ISSUE THREAD

**Issue by adonskoy** [keephq/keep#3922]
**Describe the bug**
The current implementation of the provider tries to get the repository URL from [spec.source.repoURL for each application](https://github.com/keephq/keep/blob/5a11c90e156ee26a32d6caa7c587128b8e96afbc/keep/providers/argocd_provider/argocd_provider.py#L213). However, this field became optional with the introduction of [multiple sources ](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/) in argocd. Because of this, the provider cannot pull applications and crashes with an error that it cannot find such a key

**To Reproduce**

1. Create application in argocd with multiple sources
2. Add provider in keep
4. See error (Note: some of multi-source applications have source and empty repoUrl in it, so it may be hard to reproduce from fist try)

**Expected behavior**
Respect application metadata for multi source apps

**Screenshots**

**Additional context**

**Comment by shahargl** [comment]
Hey! Thanks for the report. I will have a look.
Meanwhile can you share some logs/screenshots or the ArgoCd config so I’ll be able to reproduce?

**Comment by nodnarbnitram** [comment]
I think I'm experiencing the same issue trying to use Keep.
```json
{
  "asctime": "2025-03-07 16:24:00,158",
  "message": "Error pulling topology from provider argocd (2310684555bf4791878605af48c34113)",
  "levelname": "ERROR",
  "name": "keep.api.routes.topology",
  "filename": "topology.py",
  "otelTraceID": "ee05a6c07fba4434321b10d703237ba4",
  "otelSpanID": "43f4034899315151",
  "otelTraceSampled": true,
  "otelServiceName": "keep-api",
  "threadName": "AnyIO worker thread",
  "process": 21,
  "module": "topology",
  "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/api/routes/topology.py\", line 192, in pull_topology_data\n    provider_class.pull_topology()\n  File \"/venv/lib/python3.11/site-packages/keep/providers/argocd_provider/argocd_provider.py\", line 213, in pull_topology\n    repository=spec[\"source\"].get(\"repoURL\"),\n               ~~~~^^^^^^^^^^\nKeyError: 'source'",
  "provider_type": "argocd",
  "provider_id": "2310684555bf4791878605af48c34113",
  "tenant_id": "keep",
  "error": "'source'"
}
```
An example of one of our applicationSets

```yaml
project: default
destination:
  namespace: argocd
  name: in-cluster
syncPolicy:
  syncOptions:
    - CreateNamespace=true
sources:
  - repoURL: 'https://github.com/<redacted>/helm-charts.git'
    targetRevision: prod
    ref: values
  - repoURL: 'https://<redacted>.github.io/helm-charts'
    targetRevision: 0.1.52
    helm:
      valueFiles:
        - $values/charts/ephemeral/deploy/production.yaml
      values: |-
        environment:
          branch: "production"
          name: "production"
          sha: latest
        argo:
          applications:
            project: production
            destination:
              namespace: 'production'
              name: 'prod'
    chart: ephemeral
```

When you have multiple sources for an application the key `source` isn't used and instead `sources` is used.
