### ISSUE TITLE
[🐛 Bug]: Workflow step's body is not rendered in the editor

### ISSUE THREAD

**Issue by Matvey-Kuk** [keephq/keep#4088]
Reported by community here: https://getkeep.slack.com/archives/C04PT44MATS/p1742277804447759

![Image](https://github.com/user-attachments/assets/c39aa431-5897-4861-a3eb-c54da6481cb8)

```
workflow:
  id: incidents2feishu
  name: incidents2feishu
  description: create a ticket in feishu when an incidents is triggered
  disabled: false
  triggers:
    - type: incident
      events:
        - created
  consts: {}
  owners: []
  services: []
  steps:
    - name: webhook-step
      provider:
        type: webhook
        config: “{{ providers.feishu-bot }}”
        with:
          body:
            agent_id: ou_036f2ff9187e01e440e95a629abaef6c,ou_cd64af8ce45dbdd1ef27bf618873d627
            open_id: ou_fb76c090f7010d57d5637e9d97389bb9
            事件名称: “{{ incident.name }}”
            事件描述: “{{ incident.user_summary }}”
            事件来源: “{{ incident.alert_sources }}”
            事件状态: “{{ incident.status }}”
            事件等级: “{{ incident.severity }}”
            告警数量: “{{ incident.alerts_count }}”
          method: POST
          url: http://10.100.55.3:8000/alert
  actions: []
```
