### ISSUE TITLE
[🐛 Bug]: Log level "ERROR" logging requests

### ISSUE THREAD

**Issue by korolenkowork** [keephq/keep#4225]
### Description of the bug

I am running **Keep API** in a **GKE cluster** using `gunicorn` with `uvicorn.workers.UvicornWorker`. Even though I have explicitly set `--log-level error` and env.LOG_LEVEL, I still see **request logs** being written.  

This is my backend configuration:  
```yaml
backend:
  waitForDatabase:
    port: 5432
  image:
    repository: {{ .StateValues.registry.container }}/external-images/keephq/keep/keep-api
    tag: "0.38.8"
    pullPolicy: IfNotPresent
  env:
   # Set this to your desired log level (debug, info, warning, error)
    LOG_LEVEL: "ERROR"  
    ... ENVIRONMENT
  command:
    - "gunicorn"
  args:
    - "keep.api.api:get_app"
    - "--bind"
    - "0.0.0.0:8080"
    - "--workers"
    - "4"
    - "-k"
    - "uvicorn.workers.UvicornWorker"
    - "-c"
    - "/venv/lib/python3.11/site-packages/keep/api/config.py"
    - "--preload"
    - "--log-level"
    - "error"
```
Even with this setup, I still see logs like:  
```
2025-03-26 02:40:27,994 - ed2fe37e16ebbe9bd21236fdc5f887a8 - MainThread - 10.32.7.18:49360 - "GET /incidents/facets HTTP/1.1" 200
```

#### **Expected Behavior**  
- Setting `--log-level error` should **suppress request logs**.  
- No access logs should be printed unless an actual error occurs.  

#### **Actual Behavior**  
- Request logs are still being written, despite using `--log-level error`.  

### Steps To Reproduce

1. Deploy Keep API in a GKE cluster with the configuration above.  
2. Make a request to the API.  
3. Observe that request logs are still being generated.  

Thanks! 🚀  

Related issue https://github.com/keephq/helm-charts/issues/146#issue-2948285404
