### ISSUE TITLE
[🐛 Bug]: Error 'Failed to enrich alert in db' while using ElasticSearch as a database.

### ISSUE THREAD

**Issue by dhr05074** [keephq/keep#4305]
**Describe the bug**
In an environment where ElasticSearch is used as the database for Keep, a 404 error occurs when trying to enrich an alert in the Workflow.

**To Reproduce**

1. Write code that uses `enrich_alert` to enrich an alert in a Workflow triggered by an alert.  
2. Execute the Workflow.  
3. A 404 error occurs.

**Expected behavior**
A 404 error should not occur — the alert should be enriched successfully.

**Screenshots**
![Image](https://github.com/user-attachments/assets/af7fbb8b-72fc-4d87-97e2-eabf9d5356b0)

**Additional context**
Sample workflow:
```yaml
workflow:
  id: enrich-alert
  description: "Enrich Alert"
  triggers:
    - type: alert
      filters:
        - key: dismissed
          value: false
  actions:
    - name: set-image-url
      if: "not {{ alert.image_url }}"
      provider:
        type: mock
        with:
          enrich_alert:
            - key: image_url
              value: "{{ alert.imageUrl }}"
```
