### ISSUE TITLE
[🐛 Bug]: Installed providers disappear periodically

### ISSUE THREAD

**Issue by roma55443** [keephq/keep#4398]
**Describe the bug**
Installed providers disappear periodically, causing errors when executing workflows.
The same behavior is observed with secrets.
As a result, workflows sometimes fail due to missing providers or secrets.

**To Reproduce**
	1.	Create an installed provider.
	2.	Refresh the page multiple times. Eventually, the installed providers list appears empty.

**Expected behavior**
Installed providers and secrets should not disappear when refreshing the page.

**Video**
Installed providers bug:

https://github.com/user-attachments/assets/13f6cf1f-195a-4c77-ab64-5b9a611f74a6

Keep Secrets bug:

https://github.com/user-attachments/assets/4bf0f31a-05cf-42ae-8c5d-af46a3935200

**Additional context**
Due to this issue, we cannot use Keep in a production environment, as workflows occasionally fail with provider or secret errors.

KeepHQ version: 0.41.5

**Comment by talboren** [comment]
@roma55443 im sorry to hear that! That’s definitely nothing we observed before and does not reproduce on my end. May I know how are you deploying Keep? Can you share backend env variables maybe?

**Comment by Knyage** [comment]
@talboren We have deployed KeepHQ to kubernetes via helm. 

env backaend: 
```yaml
env:
    - name: SECRET_MANAGER_TYPE
      value: k8s
    - name: PORT
      value: "8080"
    - name: PUSHER_APP_ID
      value: 1
    - name: PUSHER_APP_KEY
      value: keepappkey
    - name: PUSHER_APP_SECRET
      value: keepappsecret
    - name: PUSHER_HOST
      value: keep-websocket
    - name: PUSHER_PORT
      value: 6001
    - name: POSTHOG_DISABLED
      value: true
```

This problem is very critical and is blocking us :(
