### ISSUE TITLE
[🐛 Bug]:

### ISSUE THREAD

**Issue by larsassink** [keephq/keep#4520]
**Describe the bug**
Unable to set the URL for the webhook properly.

**To Reproduce**

Follow Docker documentation and set the URL for the API.

**Expected behavior**
 It gives me the following url: http://keep.example.com:8080/alerts/event instead of: http://keep.example.com/alerts/event

**Additional context**
docker-compose.yml:
```
services:
  keep-frontend:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    environment:
      - AUTH_TYPE=DB
      - NEXTAUTH_SECRET=1234
      - API_URL=https://keep.example.com
    volumes:
      - ./state:/state
    depends_on:
      - keep-backend

  keep-backend:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-api
    environment:
      - AUTH_TYPE=DB
      - KEEP_JWT_SECRET=1234
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus
      - KEEP_METRICS=true
      - KEEP_HOST=keep-api.example.com
    volumes:
      - ./state:/state
```

docker-compose.common.yml:

```
services:
  keep-frontend-common:
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=1234
      - NEXTAUTH_URL=https://keep.example.com
      - NEXT_PUBLIC_API_URL=https://keep-api.example.com
      - POSTHOG_KEY=phc_muk9qE3TfZsX3SZ9XxX52kCGJBclrjhkP9JxAQcm1PZ
      - POSTHOG_HOST=https://ingest.keephq.dev
      - NEXT_PUBLIC_SENTRY_DSN=https://0d4d59e3105ffe8afa27dcb95a222009@o4505515398922240.ingest.us.sentry.io/4508258058764288
      - PUSHER_HOST=localhost
      - PUSHER_PORT=6001
      - PUSHER_APP_KEY=keepappkey

  keep-backend-common:
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=sqlite:////state/db.sqlite3?check_same_thread=False
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PUSHER_APP_ID=1
      - PUSHER_APP_KEY=keepappkey
      - PUSHER_APP_SECRET=keepappsecret
      - PUSHER_HOST=keep-websocket-server
      - PUSHER_PORT=6001
      - USE_NGROK=false
```
