### ISSUE TITLE
[➕ Feature]:  Secure Docker Socket Access via Socket-Proxy

### ISSUE THREAD

**Issue by shatovilya** [keephq/keep#4683]
Is your feature request related to a problem? Please describe.

Currently, some compose.yml files grant containers direct access to the Docker socket (/var/run/docker.sock). This poses a significant security risk, as unrestricted access to the Docker socket allows containers to gain full control over the host system.
Describe the solution you'd like

Instead of exposing the raw Docker socket, I propose using [linuxserver/socket-proxy](https://hub.docker.com/r/linuxserver/socket-proxy) as a secure intermediary. This proxy:

    Limits API calls to only those explicitly required (e.g., container start/stop, but not host-level operations).

    Reduces attack surface while maintaining necessary functionality.

Describe alternatives you've considered

    Manual API restrictions: Manually configuring Docker’s API permissions is complex and error-prone.

    Read-only socket access: This is insufficient for use cases requiring controlled write operations.

Additional context

    The socket-proxy container is maintained by LinuxServer.io and widely trusted in the community.

    Example implementation in compose.yml:

```
services:
  socket-proxy:
    image: linuxserver/socket-proxy
    networks:
      - internal_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ALLOWED_METHODS=GET,POST,HEAD
      - ALLOWED_ENDPOINTS=/containers/create,/containers/start
  
  app:
    depends_on:
      - socket-proxy
    networks:
      - internal_net
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
```
I consider it a good solution, if possible.
