### ISSUE TITLE
[🐛 Bug]: Cannot trigger keep alerts: `Failed to run step keep-action with error dictionary update sequence element #0 has length 1; 2 is required`

### ISSUE THREAD

**Issue by akire0ne** [keephq/keep#4799]
**Describe the bug**
I cannot create keep alerts in workflows.

It seems to happen where `steps` are set, and works fine if no `steps`

**To Reproduce**

The above works: https://github.com/keephq/keep/blob/main/examples/workflows/create_alert_in_keep.yml

When we add a single steps, e.g.

```
workflow:
  id: ea6cd162-b357-471f-9161-62332d347462
  name: Grafana X kv
  description: This compares grafana alert metadata with postgres query
  disabled: false
  triggers:
    - type: alert
      cel: source == "grafana" && alertname.contains("Device Unreachable")
  inputs: []
  consts: {}
  owners: []
  services: []
  steps:
    - name: postgres-step
      provider:
        type: postgres
        config: "{{ providers.k/v - dev }}"
        with:
          query: <CENSORED>
  actions:
    - name: keep-action
      provider:
        type: keep
        config: "{{ providers.default-keep }}"
        with:
          if: "{{ steps.postgres-step.results.0.1 }} == {{ alert.hostname }}"
          alert:
            name: Packloss for host in production !
            description: This host reports packet loss and is registered as production in DB
            severity: critical
```

`keep-action` fails with

```
2025-05-15T10:36:56: Running action keep-action

2025-05-15T10:36:56: Action keep-action evaluated to run! Reason: no condition, hence true.

2025-05-15T10:36:56: Checking throttling for action keep-action

2025-05-15T10:36:56: Action keep-action is not throttled

2025-05-15T10:36:56: Running keep-action StepType.ACTION, current retry: 0

2025-05-15T10:36:56: Notifying Alerts

2025-05-15T10:36:56: No 'if' condition - triggering all alerts

2025-05-15T10:36:56: Building alert DTOs

2025-05-15T10:36:56: Failed to run step keep-action with error cannot convert dictionary update sequence element #0 to a sequence
```

**Expected behavior**
The alert should be triggered

**Screenshots**

![Image](https://github.com/user-attachments/assets/4232cdcb-f015-4f91-9bde-e7589f9a4503)

**Additional context**
We run Version: 0.43.12 | Build: 3a89c1

Deployed with official helm chart.

I think it's a critical feature to have, and seems like this is not working as intended.

**Comment by shahargl** [comment]
@akire0ne the `if` should be outside ot the `with` block.

**Comment by akire0ne** [comment]
> [@akire0ne](https://github.com/akire0ne) the `if` should be outside ot the `with` block.

It does not solve the issue, as even without any `if` condition the same behavior is seen.

I've noticed it only happens when `steps` is not empty. Example

```
workflow:
  id: f9af5194-4aa0-4969-9e42-e01519e4ed82
  name: Alert SImple
  description: Alert SImple
  disabled: false
  triggers:
  - type: manual
  inputs: []
  owners: []
  services: []
  consts: {}
  steps: []
  actions:
  - name: create-alert
    provider:
      type: keep
      config: "{{ providers.default-keep }}"
      with:
        alert:
          name: Alert created from the workflow
          description: This alert was created from the create_alert_in_keep.yml example workflow.
          labels:
            environment: production
```

![Image](https://github.com/user-attachments/assets/50463fda-0832-4561-8f53-494caf0a5323)

But as soon as `steps` has an item:

```
workflow:
  id: f9af5194-4aa0-4969-9e42-e01519e4ed82
  name: Alert SImple
  description: Alert SImple
  disabled: false
  triggers:
  - type: manual
  inputs: []
  owners: []
  services: []
  consts: {}
  steps:
  - name: postgres-step
    provider:
      type: postgres
      config: "{{ providers.k/v - dev }}"
      with:
        query: < some arbitrary sql query >
  actions:
  - name: create-alert
    provider:
      type: keep
      config: "{{ providers.default-keep }}"
      with:
        alert:
          name: Alert created from the workflow
          description: This alert was created from the create_alert_in_keep.yml example workflow.
          labels:
            environment: production
```

![Image](https://github.com/user-attachments/assets/1bfa6ecf-13c0-4514-b73f-1dfb67eba9c2)
