### ISSUE TITLE
[🐛 Bug]: lookup by name when updating workflow from workflow

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#4863]
Use case:
User stores workflow yamls on s3 and want to regularly sync them from s3 to keep. He uses https://github.com/keephq/keep/blob/main/examples/workflows/update_workflows_from_s3.yml

Problem:
The workflow will duplicate every workflow because internally it looks up by id and id is random uuid assigned at creation.

Additionally, if user tries to use optional step to delete previous workflows, he will see error:

```yaml
    # optional: delete all other workflows before updating for full sync
     - name: delete-all-other-workflows
       provider:
         type: keep
         with:
           delete_all_other_workflows: true
```

<img width="1037" alt="Image" src="https://github.com/user-attachments/assets/2d200632-ddc3-4ba4-b6f9-731f61fcbc89" />
