### ISSUE TITLE
[🐛 Bug]: S3 Sync Workflow Fails to Upload Workflows to Keep

### ISSUE THREAD

**Issue by RGadi9360** [keephq/keep#4885]
**Describe the bug**
keep Version: 0.44.0 

When running the S3 sync workflow to upload workflows to Keep, the process logs shows success, but preventing successful uploads.

**To Reproduce**

1. using https://github.com/keephq/keep/blob/main/examples/workflows/update_workflows_from_s3.yml
 the Run an S3 sync workflow to upload workflows to Keep.
2. Observe that the upload process fails without successfully transferring the workflows.

**Expected behavior**
S3 sync should correctly upload workflows to Keep to match the files in the s3 bucket and keep to make sure sync successful. 

**Screenshots**

**Additional context**
This issue impacts workflow management and automation. Investigating logs may help identify the root cause.

**Comment by Kiryous** [comment]
hey @RGadi9360! the issue should be solved in the latest version, please try `0.44.7`, also make sure not to include `delete_all_other_workflows` parameters in the same step with `workflow_to_update_yaml` if this step uses `foreach`, as it will delete previously added workflows on each iteration:

## ❌ Won't work
```yaml
workflow:
  id: s3-workflow-sync
  name: S3 Workflow Sync
  description: Synchronizes Keep workflows from S3 bucket storage with optional full sync capabilities.
  triggers:
    - type: manual
  steps:
    - name: s3-dump
      provider:
        config: "{{ providers.s3 }}"
        type: s3
        with:
          bucket: "keep-workflows"
  actions:
      foreach: "{{ steps.s3-dump.results }}"
      provider:
        type: keep
        with:
          delete_all_other_workflows: true
          workflow_to_update_yaml: "raw_render_without_execution({{ foreach.value }})"
```  

## ✅ Will work
```yaml
workflow:
  id: s3-workflow-sync
  name: S3 Workflow Sync
  description: Synchronizes Keep workflows from S3 bucket storage with optional full sync capabilities.
  triggers:
    - type: manual
  steps:
    - name: s3-dump
      provider:
        config: "{{ providers.s3 }}"
        type: s3
        with:
          bucket: "keep-workflows"
  actions:
     optional: delete all other workflows before updating for full sync
     - name: delete-all-other-workflows
       provider:
         type: keep
         with:
           delete_all_other_workflows: true
    - name: update
      foreach: "{{ steps.s3-dump.results }}"
      provider:
        type: keep
        with:
          workflow_to_update_yaml: "raw_render_without_execution({{ foreach.value }})"
```
