### ISSUE TITLE
[➕ Feature]: Enrich from workflows with arrays

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#4934]
support smth like:

```
enrich_alert:
                - key: originalSource
                  value: results[0][0].message.source
                - key: messageId  
                  value: results[0][0].message._id
            command_output: 
                - 
                    - message:
                        source: "server-01"
                        level: "ERROR"
                        content: "Database connection failed"
                        _id: "msg123"
```
