### ISSUE TITLE
[🐛 Bug]: Unable to access previous results. Error message received: You can't access the results of a step that appears after the current step.

### ISSUE THREAD

**Issue by PauAmetller** [keephq/keep#4950]
**Describe the bug**
The Telegram action fails to access the result of a previous step (python-step).
An error is thrown indicating a step access order violation:
(telegram-action: Variable: '{{steps.python-step.results}}' - You can't access the results of a step that appears after the current step.)

**To Reproduce**

Run a similar workflow to this:

```yaml
workflow:
  id: keep to Telegram SQl
  name: Send keep alerts to telegram (SQL)
  description: Keep to Telegram
  disabled: false
  triggers:
    - type: interval
      value: 4h
  inputs: []
  consts: {}
  owners: []
  services: []
  steps:
    - name: query-postgres
      provider:
        type: postgres
        config: "{{ providers.PostgreSQL }}"
        with:
          query: SELECT alert_ FROM alert_time WHERE last_send > NOW() - INTERVAL '4 hours';
    - name: python-step
      provider:
        type: python
        config: "{{ providers.default-python }}"
        with:
          code: "{ d[0]: d[0] for d in {{ steps.query-postgres.results }} }"
    - name: query-keep
      if: "{{ vars.n }} > 0 "
      provider:
        type: keep
        config: "{{ providers.default-keep }}"
        with:
          version: 2
          filter: name == 'Alert K'
      vars:
        n: keep.len({{steps.query-postgres.results}})
  actions:
    - name: telegram-action
      foreach: "{{ steps.query-keep.results}}"
      if: "keep.dictget({{steps.python-step.results}} , '{{foreach.value.fingerprint}}', 'default') == '{{foreach.value.fingerprint}}'"
      provider:
          type: telegram
          config : " {{ providers.Telegram }}
          with:
              chat_id: 000000000
              message: example
```

**Expected behavior**
Access the dictionary returned from python-step (In steps.python-step.results)

Evaluate the conditional using keep.dictget(...)

Send messages only for fingerprints found in the dictionary

**Screenshots**

![Image](https://github.com/user-attachments/assets/8fdfeb66-9703-48b1-8bb3-ae95cb4604bb)
