### ISSUE TITLE
[🐛 Bug]: `{workflow_id}/run` endpoint returns 500 if there's an error in yaml def

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#4959]
If you will try to run workflow with the following provider config:
```yaml
  steps:
    - name: trace-logs
      provider:
        type: webhook
        config: "{{ providers['Quickstart Webhook'] }}"
        with:
```
you will only see uninformative`Failed to run workflow` error:
<img width="364" alt="Image" src="https://github.com/user-attachments/assets/6b67e6f4-319d-4937-8572-bcca5bf2a9fb" />

Only admins can see actual problem:

<img width="1092" alt="Image" src="https://github.com/user-attachments/assets/39ce4474-9a4e-4695-a299-4b688073cb9d" />
