### ISSUE TITLE
[🐛 Bug]: Nested foreach, the second foreach looping over the same results gives an error.

### ISSUE THREAD

**Issue by PauAmetller** [keephq/keep#5016]
**Describe the bug**
when using foreach for 2 different action steps iterating over the results of the same previous step, when doing the second foreach it says that argument type of NoneType is not iterable.

**To Reproduce**

1. Create a workflow with a step that outputs a list (e.g., users).
2. Add two separate actions that each use foreach to iterate over the output of that step.
3. Observe that during the Workflow Execution Results, the first action executes correctly, but the second one fails with a NoneType error.

Example:

```yaml
actions:
    - name: add-to-DB
      foreach: "{{ steps.python-step.results.users }}"
      provider:
        type: postgres
        config: "{{ providers.postgres }}"
        with:
          query: query
    - name: create-alert
      foreach: "{{ steps.python-step.results.users }}"
      provider:
        type: keep
        config: "{{ providers.default-keep }}"
        with:
          override_source_with: elastic
          read_only: true
          alert:
            name: alert
            description: "{{}}"
            severity: info
            labels:
              description: "{{foreach.value.description}}"
          fingerprint: "{{foreach.value.user}}"
```

**Expected behavior**
Both actions should independently iterate over the same list without error.

**Screenshots**

![Image](https://github.com/user-attachments/assets/378fff75-ed91-4ed7-9d8f-2f74839783fa)

**Comment by Kiryous** [comment]
hey @PauAmetller! Thanks for reporting the bug. I'm trying to reproduce it, but similar workflow works fine on my side. 
Can you please share your python step?

**Comment by PauAmetller** [comment]
Yes, of course, here it is.

```yaml
steps:
  - name: elastic-step
    provider:
      type: elastic
      config: "{{ providers.Elastic }}"
      with:
        index: index_*
        query:
          size: 1000
          query:
            bool:
              must:
                - match:
                    source: ACC
                - range:
                    updated_at:
                      gte: now-8h

  - name: python-step
    if: keep.len({{ steps.elastic-step.results }}) > 0
    provider:
      type: python
      config: "{{ providers.default-python }}"
      with:
        code: "{ 'users': [{ 'user': d['_source']['name'][ d['_source']['name'].index('Username ') + len('Username ') : d['_source']['name'].index(' -', d['_source']['name'].index('Username ') + len('Username '))] if 'Username ' in d['_source']['name'] else d['_source']['name'][ d['_source']['name'].index('Detected: ') + len('Detected: ') : d['_source']['name'].index(':', d['_source']['name'].index('Detected: ') + len('Detected: '))], 'name': d['_source']['name'], 'description':  d['_source']['description']} for d in {{ steps.elastic-step.results }}]}"
```
 'users': [{ 'user': d['_source']['name'][ d['_source']['name'].index('Username ') + len('Username ') : d['_source']['name'].index(' -', d['_source']['name'].index('Username ') + len('Username '))] if 'Username ' in d['_source']['name'] else d['_source']['name'][ d['_source']['name'].index('Detected: ') + len('Detected: ') : d['_source']['name'].index(':', d['_source']['name'].index('Detected: ') + len('Detected: '))],  this is just to get a word inside the name entry string paragraph.

**Comment by Kiryous** [comment]
@PauAmetller, thank you for providing the YAML! I see that the Python step only runs if the Elastic step returned something. 

In the execution that failed, may it be that the elastic step didn't return anything, so the Python step didn't run? May you also share the logs (stripped of sensitive info) for the whole workflow?

**Comment by PauAmetller** [comment]
![Image](https://github.com/user-attachments/assets/2f06a362-ab7b-488e-a262-7c27b954954b)

![Image](https://github.com/user-attachments/assets/ea878635-1126-42b0-9a4b-fc80ce4c05ec)

![Image](https://github.com/user-attachments/assets/42a1d9dc-8aeb-4023-a452-1e75748d6d20)

![Image](https://github.com/user-attachments/assets/5e05cab7-7e96-488b-9983-30e6024d3377)

**Comment by Kiryous** [comment]
@PauAmetller thank you! Continuing investigating. Will keep you in loop

**Comment by Kiryous** [comment]
@PauAmetller another follow-up question, in your definition, you have 
```yaml
    - name: create-alert
      ...
      provider:
        with:
          alert:
             ...
            description: "{{}}"
``` 

did you removed something from description or is it how it looks at the actual workflow?
