### ISSUE TITLE
[🐛 Bug]: python code got parsed into yaml when test run

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#5030]
**Describe the bug**
If I return a dict from python step, the code is parsed into dict instead of staying string resulting in python-step error. Happens only when test running, with manual run `Run now` works as intended.

**To Reproduce**

1. Create workflow with the following python-step:
```yaml
workflow:
  id: ede4b9cd-70be-44f1-bc19-fa7f7f87323b
  name: iterating twice
  description: iterating twice
  disabled: false
  triggers:
    - type: manual
  inputs: []
  consts: {}
  owners: []
  services: []
  steps:
    - name: python-step
      provider:
        type: python
        config: "{{ providers.default-python }}"
        with:
          code: '{"users": [{"description": "first", "user": "john.doe@gmail.com"}]}'
```
2. Click on `Test Run`
3. See error `unhashable type: 'dict'` and workflow definition changed, `code` transformed into a parsed yaml representation of dict.

<img width="1609" alt="Image" src="https://github.com/user-attachments/assets/5d56df19-db1a-498f-98cc-3ac0cadfdc65" />

**Expected behavior**
If run via `Run now` works just fine, code stays the string, the same should happen on test run.

<img width="2051" alt="Image" src="https://github.com/user-attachments/assets/a00ad49e-71bb-42e4-becf-2767f4b7ab4f" />
