### ISSUE TITLE
[🐛 Bug]: Time_delta in keep provider

### ISSUE THREAD

**Issue by PauAmetller** [keephq/keep#5060]
**Describe the bug**
When using the time_delta parameter in the Keep provider, the expected behavior is to filter alerts based on how many days ago they were triggered. However, specifying fractional days (e.g., 0.1667 for approximately 4 hours) does not appear to correctly filter alerts by time. Returns alerts triggered farther ago than the defined (e.g. 4 hours). Even when the time_delta is not fractional, an integer it also does not seem to work.

**To Reproduce**

```yaml
steps:
  - name: query-keep
    provider:
      type: keep
      config: "{{ providers.default-keep }}"
    with:
      version: 2
      time_delta: 0.1667  # Expecting this to represent ~4 hours
      filter: name == "XXXX"
```

**Expected behavior**
The time_delta: 0.1667 should filter alerts to include only those triggered within the last 4 hours (0.1667 days). Combined with the filter clause, the step should return only alerts with the name "XXXX" that were triggered within that time frame. But time_delta appears to have no effect. Alerts outside the expected time window are still returned.

**Screenshots**

Log:
![Image](https://github.com/user-attachments/assets/f05a632a-90c2-434f-ae06-4b40621eca72)

Yaml:
![Image](https://github.com/user-attachments/assets/43257132-adbf-4e5a-8810-a8c03b1aedad)

One of selected alerts info:
![Image](https://github.com/user-attachments/assets/99b92be0-9edc-4070-9e3c-cb9739ee67f9)
