### ISSUE TITLE
[🐛 Bug]: Incident made enrichments via workflow aren't visible when using mysql

### ISSUE THREAD

**Issue by Kiryous** [keephq/keep#5097]
**To Reproduce**

1. Create a workflow:
```yaml
workflow:
  id: incident-metadata-enricher
  name: Incident Metadata Enricher
  description: Enriches incidents with additional metadata including environment, incident IDs, URLs, and provider information while logging incident details.
  disabled: false
  triggers:
    - type: manual
    - events:
        - created
        - updated
      type: incident
  consts: {}
  owners: []
  services: []
  steps: []
  actions:
    - name: mock-step
      provider:
        type: mock
        with:
          enrich_incident:
            - key: jira_ticket
              value: "12345"
```
2. Create an incident.
3. Go to incident detail page and see that no jira_ticket field is visible.
4. See table alertenrichment in mysql has the enrichments. 

**Expected behavior**
Enrichments are visible, like when added manually via `add field` button on detail view.
