### ISSUE TITLE
[🐛 Bug]: Updating custom fields using the Jira provider returns an error

### ISSUE THREAD

**Issue by piekarski-mateusz** [keephq/keep#5121]
**Describe the bug**
Updating a Jira ticket with new custom field values returns the following error:
2025-06-30T10:06:56.976000: Updating an issue...

2025-06-30T10:06:57.111000: Failed to run step jira-action with error Failed to notify jira: Failed to update an issue: string indices must be integers, not 'str' - Params: {'summary': 'Update summary of an issue', 'description': '', 'issue_type': 'Task', 'project_key': 'FOA'}

**To Reproduce**

1. Create a workflow with the following YAML:
```
workflow:
  id: update-jira-endtime-on-resolve
  name: Update Jira ticket on Resolved
  description: Set end time on Jira ticket when incident is resolved
  disabled: false
  triggers:
    - type: incident
      events:
        - updated
  inputs: []
  consts: {}
  owners: []
  services: []
  steps: []
  actions:
    - name: jira-action
      provider:
        type: jira
        config: "{{ providers.jira }}"
        with:
          issue_id: "{{ incident.ticket_id }}"
          project_key: FA
          board_name: FA
          summary: Update summary of an issue
          custom_fields:
            customfield_10696: "10"
```

2. Run the workflow

**Expected behavior**
I expect the workflow to update the Jira ticket's custom fields.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c1fb9efd-5df4-4509-88ad-292a90503a60)
