### ISSUE TITLE
Resend Email Template Issue

### ISSUE THREAD

**Issue by ahmetcanturan** [keephq/keep#836]
**Hello** **Everyone**
I have a problem when using Bash provider and Resend provider. I cannot send html template as mail, it is sent as text.

**Sent** **mail**
![image](https://github.com/keephq/keep/assets/115570807/36e66e24-5bcc-4788-8f16-f6c38135583c)

**Mail** **should** **look** **like** **this** 
![image](https://github.com/keephq/keep/assets/115570807/58f5b032-6deb-42c2-b342-9c5f4a67f2c2)

**Workflow** **here**
```
workflow:
  id: Resend-Python-service
  description: Python Resend Mail
  triggers:
  - type: manual
  owners: []
  services: []
  steps:
  - name: run-script
    provider:
      config: '{{ providers.default-bash }}'
      type: bash
      with:
        command: python3 /app/scripts/feed-checker-scripts/main.py
        timeout: 10
  actions:
  - condition:
    - assert: '{{ steps.run-script.results.return_code }} == 0'
      name: assert-condition
      type: assert
    name: trigger-resend
    provider:
          type: resend
          config: "{{ providers.resend-test }}"
          with:
            _from: "onboarding@resend.dev"
            to: "ahmetcanturan.dev@gmail.com"
            subject: "Python test is up!"
            html: '{{ steps.run-script.results.stdout }}'
```

**KeepHQ output here** 
```[
  {
    "stdout": "<html><table style=\"font-family: arial, sans-serif; border-collapse: collapse; width: 100%;\"><tr><th style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">Agency</th><th style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">Folder</th><th style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">Status</th><th style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">Description</th></tr><tr style=\"background-color: #dddddd;\"><td style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">XX</td><td style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\">/home/xx</td><td style=\"border: 1px solid #dddddd; text-align: left; padding: 8px; color: red;\"><b>not active</b></td><td style=\"border: 1px solid #dddddd; text-align: left; padding: 8px;\"><b>it doesn't work</b></td></tr></table></body></html>",
    "stderr": "",
    "return_code": 0
  }
]
```
