### ISSUE TITLE
feat: reusable actions

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#854]
Define actions once, re-use them in different workflows.

Some context:

From `workflow.yaml`:
```
...
- name: 
  use: @action-id
...
```
and some `action.yaml` with:
```
actions:
  - id: do-something
    ...
  - id: do-something-2
 ```

**Comment by devblin** [comment]
hey @shahargl , can I pick this feature?

**Comment by devblin** [comment]
> > hey @shahargl , can I pick this feature?
> 
> Absolutely! Let me know if you need more details

sure, I will let you know!

**Comment by Gmin2** [comment]
can i get assigned with this @talboren

**Comment by shashank40** [comment]
@shahargl @Matvey-Kuk is there any specific Github action that you want to convert to this?
Or can you explain this issue better? Because i only see 4 workflows in KEEP repo

**Comment by Vibrat** [comment]
/attempt #854

Hi guys, I'm new here.

- Can I be assigned this? 
- And is this bug related to github workflow or our workflow mechanism?

**Comment by asr2003** [comment]
@Matvey-Kuk I had worked with similar issue of reusable workflows. Giving it a try to this issue
/attempt https://github.com/keephq/keep/issues/854

**Comment by Vibrat** [comment]
Hi all, 

I'm thinking to introduce a pre-template building to solve this problem.
Something like workflow.tmpl
```
tasks:
 - id: @ask-reusable-task
   name: Task 1
   ...

alert:
  id: aks-example
  description: aks-example
  actions:
    - name: @ask-reusable-task
```
and will build into a workflow.yml before submitting to our server
```
alert:
  id: aks-example
  description: aks-example
  actions:
     - name: Task 1
       ...
```

The purpose is to make our .yml more verbose and potentially prevent recursive problem when reading tasks. Then in next phrase we can favor devops by allowing merging multiple files to organize workflow in a repository, something like this. 

```
repo/ 
  reusable/
    task1.yml
    task2.yml
  main/ 
    workflow1.tmpl
    workflow2.tmpl
```
which we can do something like this in the future. 
```
# build the repository
keep workflow build .

# Apply configuration to our server
keep workflow apply .
```
